feat: hello bun, bye bye pnpm

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,8 +1,8 @@
 echo "Testing your code...🛠️"
 
-pnpm format:check ||
+bun format:check ||
 (
-    echo 'Prettier Check Failed. Run pnpm format, add changes and try commit again.';
+    echo 'Prettier Check Failed. Run bun format, add changes and try commit again.';
     false;
 )
 
